#!/bin/bash
# Change dir to cwd
#$ -cwd
#$ -e ./deg_txome/output
#$ -o ./deg_txome/output
#$ -N deg_txome
# Enter an array job
#$ -t 1-9
# Run from ~/workspace/deg
ProjectName="deg_txome"
ReferenceDir="/home/kevin/workspace/arabidopsis_refseqs"
ScriptDir="/home/kevin/scripts"

bwa aln -n 0 -t 24 ${ReferenceDir}/tx_tair10rep.fasta deg_${SGE_TASK_ID}.fasta > ./${ProjectName}/deg_${SGE_TASK_ID}.sai
bwa samse -n 0 ${ReferenceDir}/tx_tair10rep.fasta ./${ProjectName}/deg_${SGE_TASK_ID}.sai deg_${SGE_TASK_ID}.fasta > ./${ProjectName}/deg_${SGE_TASK_ID}.sam
samtools view -b -S -o ./${ProjectName}/deg_${SGE_TASK_ID}.bam ./${ProjectName}/deg_${SGE_TASK_ID}.sam
R --no-save -f ${ScriptDir}/filter_bam.R --args ./${ProjectName}/deg_${SGE_TASK_ID}.bam ./${ProjectName}/deg_${SGE_TASK_ID}
R --no-save -f ${ScriptDir}/plot_baseline.R --args ./${ProjectName}/deg_${SGE_TASK_ID}_filtered.csv ./${ProjectName}/deg_${SGE_TASK_ID}_targets.csv ./${ProjectName}/deg_${SGE_TASK_ID}

#htseq-count -t intergenic -i ID ./${ProjectName}/deg_${SGE_TASK_ID}.sam ${ReferenceDir}/tx_tair10rep.gff3 > ./${ProjectName}/deg_${SGE_TASK_ID}.count

